name: Publish

on:
  create:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - run: pnpm run build

#      - name: Browser Platform Publish
#        uses: PlasmoHQ/bpp@v2
#        with:
#          artifact: dist/addon.zip
#          keys: ${{ secrets.BPP_KEYS }}
