name: Publish

on:
  create:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - uses: actions/checkout@v3

      - run: npm i -g pnpm

      - run: pnpm install

      - run: pnpm run build

      - run: zip addon.zip *
        working-directory: dist

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v2
        with:
          artifact: dist/addon.zip
          keys: ${{ secrets.BPP_KEYS }}
